version: '3.8'
services:
  db:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moneycount_db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  back-api:
    container_name: back
    build:
        context: ./back
        dockerfile: Dockerfile
    ports:
        - "4000:4000"
    environment:
        - NODE_ENV=development
    depends_on:
        - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  db:
  pgadmin: