version: '3.8'
services:
  back-api:
    container_name: back
    build:
        context: ./back
        dockerfile: Dockerfile
    ports:
        - "4000:4000"
    environment:
        - NODE_ENV=development
    # depends_on:
    #     - db